{{- if and .Values.postgres.enabled (not .Values.auth.broker.database.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketship.authbroker.databaseSecretName" . }}
  labels:
    {{- include "rocketship.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-broker
    app.kubernetes.io/part-of: rocketship
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:5432/%s?sslmode=disable" (default "rocketship" .Values.postgres.auth.username) (default "" .Values.postgres.auth.password) (include "rocketship.postgresql.host" .) (default "rocketship" .Values.postgres.auth.database) | b64enc }}
{{- end }}
