# Companion values file for enabling oauth2-proxy when using the GitHub auth broker.
# Users must create the oauth2-proxy-credentials secret with client ID/secret/cookie data.

web:
  enabled: true
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: app.globalbank.rocketship.sh
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: globalbank-rocketship-tls
        hosts:
          - app.globalbank.rocketship.sh
  oauth2Proxy:
    enabled: true
    replicaCount: 1
    upstreamOverride: ""
    extraArgs:
      - --cookie-name=_rocketship_auth
      - --cookie-secure=true
      - --cookie-samesite=lax
      - --scope=read:user user:email
      - --email-domain=*
      - --skip-provider-button=true
    env:
      - name: OAUTH2_PROXY_PROVIDER
        value: oidc
      - name: OAUTH2_PROXY_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: oauth2-proxy-credentials
            key: clientID
      - name: OAUTH2_PROXY_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: oauth2-proxy-credentials
            key: clientSecret
      - name: OAUTH2_PROXY_COOKIE_SECRET
        valueFrom:
          secretKeyRef:
            name: oauth2-proxy-credentials
            key: cookieSecret
      - name: OAUTH2_PROXY_REDIRECT_URL
        value: https://app.globalbank.rocketship.sh/oauth2/callback
      - name: OAUTH2_PROXY_OIDC_ISSUER_URL
        value: https://auth.globalbank.rocketship.sh
      - name: OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER
        value: "true"
      - name: OAUTH2_PROXY_SET_AUTHORIZATION_HEADER
        value: "true"
      - name: OAUTH2_PROXY_SET_XAUTHREQUEST
        value: "true"
      - name: OAUTH2_PROXY_FORCE_HTTPS
        value: "false"
      - name: OAUTH2_PROXY_HTTPS_ADDRESS
        value: ":0"

auth:
  mode: github
