# Example values for enabling oauth2-proxy in front of the Rocketship web endpoints
# using an external IdP (Auth0, Okta, Azure AD, etc.). Update the domains, secret
# names, and client identifiers for your environment.

web:
  enabled: true
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: app.rocketship.globalbank.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: globalbank-tls
        hosts:
          - app.rocketship.globalbank.com
  oauth2Proxy:
    enabled: true
    replicaCount: 1
    upstreamOverride: ""
    extraArgs:
      - --cookie-name=_rocketship_auth
      - --cookie-secure=true
      - --cookie-samesite=lax
      - --scope=openid profile email offline_access
      - --email-domain=*
      - --skip-provider-button=true
    env:
      - name: OAUTH2_PROXY_PROVIDER
        value: github
      - name: OAUTH2_PROXY_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: oauth2-proxy-credentials
            key: clientID
      - name: OAUTH2_PROXY_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: oauth2-proxy-credentials
            key: clientSecret
      - name: OAUTH2_PROXY_COOKIE_SECRET
        valueFrom:
          secretKeyRef:
            name: oauth2-proxy-credentials
            key: cookieSecret
      - name: OAUTH2_PROXY_REDIRECT_URL
        value: https://app.rocketship.globalbank.com/oauth2/callback
      - name: OAUTH2_PROXY_OIDC_ISSUER_URL
        value: https://auth.globalbank.com/oidc
      - name: OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER
        value: "true"
      - name: OAUTH2_PROXY_SET_AUTHORIZATION_HEADER
        value: "true"
      - name: OAUTH2_PROXY_SET_XAUTHREQUEST
        value: "true"
      - name: OAUTH2_PROXY_FORCE_HTTPS
        value: "false"
      - name: OAUTH2_PROXY_HTTPS_ADDRESS
        value: ":0"

      - name: OAUTH2_PROXY_SCOPE
        value: "read:user user:email"
      - name: OAUTH2_PROXY_EMAIL_DOMAINS
        value: "*"

auth:
  mode: oidc
  oidc:
    enabled: true
    issuer: https://auth.globalbank.com/oidc
    clientID: rocketship-cli
    audience: rocketship-cli
    tokenEndpoint: https://auth.globalbank.com/oauth2/token
    deviceEndpoint: https://auth.globalbank.com/oauth/device/code
    jwksURL: https://auth.globalbank.com/.well-known/jwks.json
    scopes:
      - openid
      - profile
      - email
      - offline_access
    allowedAlgorithms:
      - RS256
  broker:
    enabled: false
