# for NGINX
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  hosts:
    - host: cli.rocketship.globalbank.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: globalbank-tls
      hosts:
        - cli.rocketship.globalbank.com
