auth:
  mode: oidc
  oidc:
    mode: github
    issuer: https://auth.rocketship.globalbank.com
    clientID: rocketship-cli
    audience: rocketship-cli
    deviceEndpoint: https://auth.rocketship.globalbank.com/device/code
    tokenEndpoint: https://auth.rocketship.globalbank.com/token
    jwksURL: https://auth.rocketship.globalbank.com/.well-known/jwks.json
    scopes:
    - read:org
    - read:user
    - user:email
  broker:
    enabled: true
    issuer: https://auth.rocketship.globalbank.com
    audience: rocketship-cli
    clientID: rocketship-cli
    scopes:
    - read:org
    - read:user
    - user:email
    github:
      clientID: your-github-client-id
      clientSecretSecret: globalbank-github-oauth
      scopes:
      - read:org
      - read:user
      - user:email
    signingKey:
      secretName: globalbank-auth-broker-signing
      key: signing-key.pem
      mountPath: /var/run/rocketship
      fileName: signing-key.pem
    store:
      path: /var/lib/rocketship/broker-store.enc
      mountPath: /var/lib/rocketship
      encryptionKeySecret: globalbank-auth-broker-store
      encryptionKeyKey: ROCKETSHIP_BROKER_STORE_KEY
      emptyDir: true
    env:
    - name: ROCKETSHIP_BROKER_ACCESS_TTL
      value: 15m
    - name: ROCKETSHIP_BROKER_REFRESH_TTL
      value: 720h
    service:
      type: ClusterIP
      port: 8080
    ingress:
      enabled: true
      className: nginx
      annotations: {}
      hosts:
      - host: auth.rocketship.globalbank.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - secretName: globalbank-tls
        hosts:
        - auth.rocketship.globalbank.com
    envFrom:
    - secretRef:
        name: globalbank-github-oauth
    - secretRef:
        name: globalbank-auth-broker-store
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
  hosts:
  - host: cli.rocketship.globalbank.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: globalbank-tls
    hosts:
    - cli.rocketship.globalbank.com
