apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: rocketship

# Build configuration - watches Go source and rebuilds images on change
build:
  artifacts:
    # Engine service
    - image: rocketship-engine-local
      context: .
      docker:
        dockerfile: .docker/Dockerfile.engine
      sync:
        # Sync Go binaries directly for faster iteration
        manual:
          - src: "cmd/engine/**/*.go"
            dest: .
          - src: "internal/**/*.go"
            dest: .
          - src: "proto/**/*.proto"
            dest: .

    # Worker service
    - image: rocketship-worker-local
      context: .
      docker:
        dockerfile: .docker/Dockerfile.worker
      sync:
        manual:
          - src: "cmd/worker/**/*.go"
            dest: .
          - src: "internal/**/*.go"
            dest: .
          - src: "proto/**/*.proto"
            dest: .

    # Auth Broker service
    - image: rocketship-authbroker-local
      context: .
      docker:
        dockerfile: .docker/Dockerfile.authbroker
      sync:
        manual:
          - src: "cmd/authbroker/**/*.go"
            dest: .
          - src: "internal/**/*.go"
            dest: .

  # Use minikube's Docker daemon
  local:
    push: false
    useBuildkit: true
    concurrency: 0

# Deploy configuration - uses Helm
deploy:
  helm:
    releases:
      - name: rocketship
        chartPath: charts/rocketship
        namespace: rocketship
        createNamespace: true
        valuesFiles:
          - charts/rocketship/values-minikube-local.yaml
        setValueTemplates:
          # Temporal configuration
          temporal.host: "temporal-frontend.rocketship:7233"
          temporal.namespace: "default"
          # Engine image
          engine.image.repository: "rocketship-engine-local"
          engine.image.tag: "dev"
          engine.image.pullPolicy: "IfNotPresent"
          # Worker image
          worker.image.repository: "rocketship-worker-local"
          worker.image.tag: "dev"
          worker.image.pullPolicy: "IfNotPresent"
          # Auth broker image
          auth.broker.image.repository: "rocketship-authbroker-local"
          auth.broker.image.tag: "dev"
          auth.broker.image.pullPolicy: "IfNotPresent"
          # CRITICAL: Engine must resolve auth.minikube.local to ingress controller
          # This IP is detected by setup-local-dev.sh and exported in .minikube-env
          # NOTE: Must set BOTH ip and hostnames because Helm --set replaces entire array element
          engine.hostAliases[0].ip: "{{.ROCKETSHIP_INGRESS_IP}}"
          engine.hostAliases[0].hostnames[0]: "auth.minikube.local"
        wait: true
        upgradeOnChange: true

# Profiles for different environments
profiles:
  # Development profile with debug logging
  - name: debug
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues
        value:
          engine.env.ROCKETSHIP_LOG: "DEBUG"
          worker.env.ROCKETSHIP_LOG: "DEBUG"
          auth.broker.env.LOG_LEVEL: "debug"
