# OIDC configuration secret
{{- if not .Values.auth.oidc.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketship.fullname" . }}-oidc
  labels:
    {{- include "rocketship.labels" . | nindent 4 }}
type: Opaque
data:
  issuer: {{ .Values.auth.oidc.issuer | b64enc }}
  {{ .Values.auth.oidc.secretKeys.clientId }}: {{ .Values.auth.oidc.clientId | b64enc }}
  {{ .Values.auth.oidc.secretKeys.clientSecret }}: {{ .Values.auth.oidc.clientSecret | default "" | b64enc }}
---
{{- end }}

# Auth database password secret
{{- if not .Values.auth.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketship.fullname" . }}-auth-db
  labels:
    {{- include "rocketship.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.database.secretKeys.password }}: {{ .Values.auth.database.password | b64enc }}
---
{{- end }}

