{{- if .Values.temporal.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "rocketship.fullname" . }}-create-namespace
  labels:
    {{- include "rocketship.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        {{- include "rocketship.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: create-namespace
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-temporal
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z {{ include "rocketship.temporal.host" . | replace ":7233" "" }} 7233; do echo "Waiting for Temporal frontend..."; sleep 5; done']
      containers:
        - name: create-namespace
          image: temporalio/admin-tools:1.25.0-tctl-1.18.1-cli-1.0.0
          command:
            - /bin/sh
            - -c
            - |
              # Check if namespace exists
              if tctl --address {{ include "rocketship.temporal.host" . }} namespace describe default >/dev/null 2>&1; then
                echo "Namespace 'default' already exists"
              else
                echo "Creating namespace 'default'"
                tctl --address {{ include "rocketship.temporal.host" . }} namespace register default
              fi
{{- end }}