FROM golang:1.24-alpine AS builder

ARG TARGETOS=linux
ARG TARGETARCH=amd64
ENV CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /bin/auth-broker ./cmd/authbroker

FROM alpine:3.16

WORKDIR /app

COPY --from=builder /bin/auth-broker /bin/auth-broker

EXPOSE 8080

ENTRYPOINT ["/bin/auth-broker"]
