name: Release CLI

on:
  push:
    tags:
      - "v*" # Trigger on version tags

permissions:
  contents: write # Needed for creating releases
  packages: write # Needed for pushing to Docker Hub

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true

      - name: Build release artifacts
        run: |
          # Create release artifacts for different platforms
          mkdir -p bin

          # Build CLI binaries
          GOOS=darwin GOARCH=amd64 go build -o bin/rocketship-darwin-amd64 cmd/rocketship/main.go
          GOOS=darwin GOARCH=arm64 go build -o bin/rocketship-darwin-arm64 cmd/rocketship/main.go
          GOOS=linux GOARCH=amd64 go build -o bin/rocketship-linux-amd64 cmd/rocketship/main.go
          GOOS=linux GOARCH=arm64 go build -o bin/rocketship-linux-arm64 cmd/rocketship/main.go
          GOOS=windows GOARCH=amd64 go build -o bin/rocketship-windows-amd64.exe cmd/rocketship/main.go

          # Build worker binaries
          GOOS=darwin GOARCH=amd64 go build -o bin/worker-darwin-amd64 cmd/worker/main.go
          GOOS=darwin GOARCH=arm64 go build -o bin/worker-darwin-arm64 cmd/worker/main.go
          GOOS=linux GOARCH=amd64 go build -o bin/worker-linux-amd64 cmd/worker/main.go
          GOOS=linux GOARCH=arm64 go build -o bin/worker-linux-arm64 cmd/worker/main.go
          GOOS=windows GOARCH=amd64 go build -o bin/worker-windows-amd64.exe cmd/worker/main.go

          # Build engine binaries
          GOOS=darwin GOARCH=amd64 go build -o bin/engine-darwin-amd64 cmd/engine/main.go
          GOOS=darwin GOARCH=arm64 go build -o bin/engine-darwin-arm64 cmd/engine/main.go
          GOOS=linux GOARCH=amd64 go build -o bin/engine-linux-amd64 cmd/engine/main.go
          GOOS=linux GOARCH=arm64 go build -o bin/engine-linux-arm64 cmd/engine/main.go
          GOOS=windows GOARCH=amd64 go build -o bin/engine-windows-amd64.exe cmd/engine/main.go

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/rocketship-darwin-amd64
            bin/rocketship-darwin-arm64
            bin/rocketship-linux-amd64
            bin/rocketship-linux-arm64
            bin/rocketship-windows-amd64.exe
            bin/worker-darwin-amd64
            bin/worker-darwin-arm64
            bin/worker-linux-amd64
            bin/worker-linux-arm64
            bin/worker-windows-amd64.exe
            bin/engine-darwin-amd64
            bin/engine-darwin-arm64
            bin/engine-linux-amd64
            bin/engine-linux-arm64
            bin/engine-windows-amd64.exe
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push CLI image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/ci-testing/Dockerfile.cli
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            rocketshipai/rocketship:${{ steps.get_version.outputs.VERSION }}
            rocketshipai/rocketship:latest

      - name: Build and push Engine image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/Dockerfile.engine
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            rocketshipai/rocketship-engine:${{ steps.get_version.outputs.VERSION }}
            rocketshipai/rocketship-engine:latest

      - name: Build and push Worker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/Dockerfile.worker
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            rocketshipai/rocketship-worker:${{ steps.get_version.outputs.VERSION }}
            rocketshipai/rocketship-worker:latest
